language: haxe

sudo: false

addons:
  apt:
    packages:
      - python3

# haxe:
#   - "3.1.3"
#   - "3.2.0"
#   - development

matrix:
  include:
    - env: TARGET=js

    - env: TARGET=cs
      install:
        - haxelib install hxcs
        - git clone https://github.com/jgm/CommonMark
      addons:
        apt:
          packages:
            - python3
            - mono-devel
            - mono-mcs

    - env: TARGET=neko

install:
  - git clone https://github.com/jgm/CommonMark

script:
  - mkdir bin
  - haxe travis.hxml
  - neko bin/travis.n
