language: haxe

haxe:
  - "3.1.3"
  - "3.2.0"
  - development

addons:
  apt:
    packages:
      - python3

install:
  - git clone https://github.com/jgm/CommonMark

script:
  - mkdir bin
  - haxe build.hxml && cd CommonMark && python3 test/spec_tests.py --program "node ../bin/test.js"
