sudo: required
dist: trusty

language: haxe

haxe:
  - "3.2.1"
  - development

addons:
  apt:
    packages:
      - python3
      - mono-devel
      - mono-mcs

install:
  - haxelib install hxcs
  - git clone https://github.com/jgm/CommonMark

script:
  - haxe travis.hxml
  - TARGET=js neko bin/travis.n
  - TARGET=cs neko bin/travis.n
