language: haxe

sudo: false

addons:
  apt:
    packages:
      - python3

# haxe:
#   - "3.1.3"
#   - "3.2.0"
#   - development

before_install:
  - git clone https://github.com/jgm/CommonMark

matrix:
  include:
    - env: TARGET=js

    - env: TARGET=cs
      install:
        - haxelib install hxcs
      addons:
        apt:
          packages:
            - mono-devel
            - mono-mcs

    - env: TARGET=java
      install:
        - haxelib install java

    #- env: TARGET=neko

install:

script:
  - mkdir bin
  - haxe travis.hxml
  - neko bin/travis.n
