language: haxe

haxe:
  - "3.1.3"
  - "3.2.0"
  - development

addons:
  apt:
    packages:
      - python3

matrix:
  include:
    - env: TARGET=js
    - env: TARGET=neko

install:
  - git clone https://github.com/jgm/CommonMark

script:
  - mkdir bin
  - haxe travis.hxml
  - neko bin/travis.n
